### ISSUE TITLE
remove logback.xml

### ISSUE THREAD

**Issue by petteyg** [sbabcoc/logback-testng#14]
WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.

The logback.xml in your released artifact causes warnings when I provide my own logback.xml for my applications.

**Comment by sbabcoc** [comment]
I moved the `logback.xml` file into the "test" hierarchy.

**Comment by sbabcoc** [comment]
Let me know if this release still show the issue
